In [1]:
# creating an array
import numpy as np

b = np.empty(2,dtype = int)
print("Matrix b:\n",b)

a = np.empty([2,2],dtype = int)
print("\nMatrix b:\n",a)

c = np.empty([3,3])
print("\nMatrix c: \n",c)

Matrix b:
 [1065353216 1065353216]

Matrix b:
 [[  801530504 -1448511703]
 [  396686476 -1257086266]]

Matrix c: 
 [[4.45035992e-308 1.42418444e-306 1.02360867e-306]
 [4.45033446e-308 1.86921143e-306 2.78151378e-307]
 [1.24610994e-306 3.44900369e-307 4.22792214e-307]]


In [3]:
import numpy as np
b = np.zeros(1,dype = int)
print('Matrix b : \n',a)

a = np.zeros([2,2],dtype = int)
print("\nMatrix a: \n",a)

c = np.zeros([3,3])
print('\nMatrix c:\n',c)

TypeError: zeros() got an unexpected keyword argument 'dype'

In [4]:
import numpy as np

# Defining both the matrices

a = np.array([5,72,13,100])
b= np.array

# Perfomring addition using arithmetic operaator
add_ans = a + b
print(add_ans)

# Performing addition using numpy function
add_ans = np.add(a,b)
print(add_ans)

# The same functions and operations can be used for
# muliple matrices

c = np.array([1,2,3,4])
add_ans = a + b + c
print(add_ans)

add_ans = np.add(a,b,c)
print(add_ans)   

TypeError: unsupported operand type(s) for +: 'int' and 'builtin_function_or_method'

In [2]:
# Python program for indexing using basic slicing elpses
import numpy as np

# A 3 dimensional array
b = np.array([[[1,2,3] ,[4,5,6]],
             [[7,8,9],[10,11,12]] ]            
             )
print(b[...,1])  # Equivalent to b [;,;,1]

[[ 2  5]
 [ 8 11]]


In [3]:
import numpy as np
macros = np.array([
 [0.8,2.9,3.9],
 [52.4,23.6,36.5],
 [55.2,31.7,23.9],
 [14.4,4.9]
])


# create a new array filled with zeros
# of the same change as macros

result = np.zeros_like(macros)

cal_per_macro = np.array([3,3,8])
# Now multiplty each row of macros by
# cal_per_macro .In numpy , `*` is
# elemnent-wise mupltiplication between two arrays
for i in range(macros.shape[0]):
 result[i,:] = macros[i,:] * cal_per_macro
 result

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.

In [4]:
import numpy as np
v = np.array([12,24,36])
w = np.array([45,55])

# to computer an outlet product we first
# reshape v to a column vector of shape 3*1
# then broadcast it aginst w to yield an output
# of shape 3*2 which is the outer product of v and w
print(np.reshape(v,(3,1))* w)

[[ 540  660]
 [1080 1320]
 [1620 1980]]


In [6]:
# Analyszing Data using Pandas
import pandas as pd
import numpy as np

# creating empty series
ser = pd.Series()

print(ser)

# simple array
data = np.array('g','e','e','k','s')

ser = pd.Series(data)
print(ser)

Series([], dtype: float64)


C:\Users\jki\AppData\Local\Temp\ipykernel_4512\2063620325.py:6: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  ser = pd.Series()


TypeError: array() takes from 1 to 2 positional arguments but 5 were given