In [1]:
# creating an array
import numpy as np

b = np.empty(2,dtype = int)
print("Matrix b:\n",b)

a = np.empty([2,2],dtype = int)
print("\nMatrix b:\n",a)

c = np.empty([3,3])
print("\nMatrix c: \n",c)

Matrix b:
 [1065353216 1065353216]

Matrix b:
 [[  801530504 -1448511703]
 [  396686476 -1257086266]]

Matrix c: 
 [[4.45035992e-308 1.42418444e-306 1.02360867e-306]
 [4.45033446e-308 1.86921143e-306 2.78151378e-307]
 [1.24610994e-306 3.44900369e-307 4.22792214e-307]]


In [3]:
import numpy as np
b = np.zeros(1,dype = int)
print('Matrix b : \n',a)

a = np.zeros([2,2],dtype = int)
print("\nMatrix a: \n",a)

c = np.zeros([3,3])
print('\nMatrix c:\n',c)

TypeError: zeros() got an unexpected keyword argument 'dype'

In [4]:
import numpy as np

# Defining both the matrices

a = np.array([5,72,13,100])
b= np.array

# Perfomring addition using arithmetic operaator
add_ans = a + b
print(add_ans)

# Performing addition using numpy function
add_ans = np.add(a,b)
print(add_ans)

# The same functions and operations can be used for
# muliple matrices

c = np.array([1,2,3,4])
add_ans = a + b + c
print(add_ans)

add_ans = np.add(a,b,c)
print(add_ans)   

TypeError: unsupported operand type(s) for +: 'int' and 'builtin_function_or_method'